### ISSUE TITLE
Implement Form Validation for User Input Fields

### ISSUE THREAD

**Issue by Pratik-09pp** [Atharv181/Gym-Website#1]
on your gym website where new users can register by filling out a form with their name, age, gender, and email address. However, there is currently no validation in place, leading to potential issues with incorrect or incomplete data submissions. To enhance the user experience and ensure data accuracy, I need to implement proper form validation for the input fields.

I Want to work on this issue.
Can you assign these to me?

**Comment by Atharv181** [comment]
Hey @Pratik-09pp thank you for raising issue.
Yes you can work on that. 
keep building
